### ISSUE TITLE
Version is missing in generated formula.

### ISSUE THREAD

**Issue by fwartner** [Justintime50/homebrew-releaser#7]
```bash
Error: invalid attribute for formula 'fwartner/tap/mac-cleanup': version (nil)
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:284:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:213:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:181:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:181:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:340:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:412:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:636:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:632:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:632:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:311:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:131:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

**Comment by Justintime50** [comment]
Thanks for reporting this!

Homebrew infers the version based on the latest release title (and therefore the version in the URL to the tar file (eg: `https://github.com/Justintime50/onepass/archive/v0.2.0.tar.gz`).

It looks like your most recent release of `mac-cleanup` has the release title of `Fixit` instead of a semantic version number (which is fine, Homebrew Releaser just doesn't know what to do with it).

You have three options to correct this, the first two would be temporary workarounds:
1. Rename your latest v1.0.8 release from `Fixit` to `v1.0.8` and re-run the GitHub Action
2. If the first step doesn't work, create a new `v1.0.9` titled release and tag which should trigger the release flow and would create the url `https://github.com/fwartner/mac-cleanup/archive/v1.0.9.tar.gz` which then would allow Homebrew to install it
3. Longerterm, I'll look into correcting this and you can attempt a re-release once this is patched. The `version` attribute was previously included in Homebrew Releaser but was removed due to Homebrew's linter throwing errors when it could reliably infer the version from the URL. I'll most likely need to include some conditional logic to automatically add the version attribute when it cannot infer the version from the url (in the case of releases that have names instead of version numbers). I plan to look into this soon but don't have an immediate ETA. There were a number of other improvements I'm currently working on for the tool and this can be included with them.

**Comment by Justintime50** [comment]
Thanks for your patience on this! Homebrew Releaser will now use the latest `tag` instead of the latest `release`. This should better align with correct versioning while still allowing users to specify a "titled" release on GitHub.

Please note that tags must follow semantic versioning for Homebrew to infer the installation instructions correctly; however, you can now retain your titled release (eg: a release title of `Fixit` with a tag of `v1.0.9` should work just fine.

To give this a whirl, simply re-run your releasing workflow or create a new tag on GitHub for your project.
